### ISSUE TITLE
Connecting via cluster (Address[])

### ISSUE THREAD

**Issue by eacarvalho** [reinhapa/rabbitmq-cdi#1]
Hi, Patrick

I would like to know how can I connect via cluster, in other words, how to configure my connection factory to accept an array of address (for instance, 192.168.0.1:6775,192.168.0.2:6775).

Something like that:

```
@Singleton
@Startup
public class BindingInitializer {
  @Inject
  private RabbitBinder binder;
  @Inject
  private ConnectionFactory connectionFactory;

  @PostConstruct
  public void initialize() {
    try {
      // connectionFactory.setHost("somehost.somedomain");
      connectionFactory.newConnection(Address[] addrs);
      binder.initialize();
    } catch (IOException e) {
      LoggerFactory.getLogger(getClass()).error("Unable to initialize", e);
    }
  }
}
```

The above code doesn't :( I believe because this part of the framework:

**EventPublisher. providePublisher** that calls **publisher = new GenericPublisher(connectionFactory)**. The class GenericPublisher has a method provideChannel() that get a new connection like that: **connectionFactory.newConnection()** without the parameter Address[] addrs that I set before. Because that, all call return the default localhost instead my **Address[] addrs**.

Could you help me how to set up cluster using your framework?

Thank you very much.

**Comment by reinhapa** [comment]
Hi Eduardo?

I see your requirement. At the moment, the actual implementation does not support a cluster configuration. The current RabbitMQ specific configuration does also not really feel right and needs definitively more improvements. I'm thinking on something like a connection provider interface getting the connection factory and returning a newly created connection, so the complete configuration can be done on the user side, or via annotation of some kind...

I will need to think this for a moment.

Cheers Patrick

**Comment by ignacio83** [comment]
Hi, Patrick

I work with @eacarvalho.

Do you have a estimate time to do this enhacement?
If you prefer, we can help with some PRs :)

What you think about?

**Comment by reinhapa** [comment]
Hi, Ignacio

I have done some local changes now to have the target host names being configurable and doing some testing now. I still not completely happy with them but it seems to work. What else do you need to configure together with the host names, user name and password?

**Comment by eacarvalho** [comment]
Patrick,
I really appreciate your prompt answer!
We need to set username and password as well, but I believe that I can set it using the normal ConnectionFactory (like **connectionFactory.setUsername("xxxxxxx")**);
What do you think?
Cheers!

**Comment by reinhapa** [comment]
Just pushed a prototype version to a separate branch [enable_cluster_addressing](https://github.com/reinhapa/rabbitmq-cdi/tree/enable_cluster_addressing). You can take a look at that and check that out. Give me feedback if that would meet your requirements.

Cheers Patrick

**Comment by eacarvalho** [comment]
Great!
The key for me is **BinderConfiguration addHost(Address hostAddress)**.
Thank you very much. As soon as you publish this version at maven central repository, could you let me know?
Lets keep in touch :)
Cheers!

**Comment by reinhapa** [comment]
Version 0.9.3 containing this enhancement now online

**Comment by eacarvalho** [comment]
Hi, great news!
Can I find the new version 0.9.3 here (http://mvnrepository.com/artifact/net.reini/rabbitmq-cdi)?
Thank you very much!
