### ISSUE TITLE
Retry if initial connection failes + allow to declare exchanges and queues

### ISSUE THREAD

**Issue by Gr33nbl00d** [reinhapa/rabbitmq-cdi#14]
We identified two issues first isssue is if the rabbitmq is initially down than no retry occurs.
This is a flaw of the underlying rabbitmq client library.

Also there is no api yet to define queues and exchanges.
I would like to add these changes and make a push request.

What do you think?

**Comment by Gr33nbl00d** [comment]
i have to correct myself retry occurs i have seen it also in the code. Problem is if we want to redeclare the queues and exchanges after connection was successfull we need to be informed before eventbinder is informed. We could try to add ourself to the ConnectionProducer as listener before the eventbinder registers itself so we are informed prior.

I would like to add an decleareconfiguration to eventbinder so we can store queue and exchange declaration and execute this after connection was successfull.

**Comment by reinhapa** [comment]
Hi @Gr33nbl00d do I understand it correctly that there is no problem with the session retry and the purpose of this issue is to add a way to dynamically configure a binding upon a connection establishment here?
If this is the case, could you change the title accordingly and we could discuss the actual implementation a bit more in detail prior implementing it.

**Comment by reinhapa** [comment]
It would be great if you do this change on a feature branch an create a pull request for it (including enhancing a junit test if possible)

**Comment by Gr33nbl00d** [comment]
I did the changes but in the end it required a bigger change. Tests are added as always.
I think i will be able to commit it on monday in another feature branch.

Thinks i changed so far:
added Exchange Declartion
added Queue Declaration
added Reconnect if broker initially down on service startup
added automatic channel recreation and consumer binding in case of channel errors (for example wrong exchange/queue definitions)
All timers are now configurable as well (connecttimeout,retry timeout, hearbeat timeout)

**Comment by reinhapa** [comment]
Sounds great, looking forward for it :-)
