### ISSUE TITLE
Consume on queue is started before declaration of queue

### ISSUE THREAD

**Issue by Gr33nbl00d** [reinhapa/rabbitmq-cdi#150]
in ComsumerHolder.activate method
channel.basicConsume is called before declarerRepository.declare
Therefore the queue is not existing and will never be created and the consumer can never be started

`          channel.basicConsume(queueName, autoAck,
              autoAck ? this::deliverNoAck : this::deliverWithAck, this::handleShutdownSignal);
          declarerRepository.declare(channel, declarations);
`

**Comment by reinhapa** [comment]
@Gr33nbl00d as we do not use this feature, feel free to create a PR for this issue if you got a good idea on how to solve if for you're usecase.
