### ISSUE TITLE
Version 0.9.11 doesn't contains setConnectTimeout(), setConnectRetryWaitTime(), setRequestedConnectionHeartbeatTimeout()

### ISSUE THREAD

**Issue by sbiermann** [reinhapa/rabbitmq-cdi#23]
Hi,
it seems the documentation (readme.md) describes a version of the lib which is not released in maven repository. I have downloaded yet the 0.9.11 from maven central and that doesn't containing the methods for setting timeout handling.

Kind regards
Stefan

**Comment by reinhapa** [comment]
The [Documentation for 0.9.x Releases](https://github.com/reinhapa/rabbitmq-cdi/tree/0.9-patch) is available in the respective branch.

There will be a new version `1.0.0-rc1`soon, that makes this configuration possible as in the current master branch.
