### ISSUE TITLE
Misleading warn message in ConnectionManager.tryToEstablishConnection()

### ISSUE THREAD

**Issue by domric** [reinhapa/rabbitmq-cdi#27]
Warn message does not pay attention to the configuration (config) in ConnectionManager.tryToEstablishConnection()#113.
Host and port of connectionFactory is set to default (localhost:5672), what is different from the configuration (xxx:5671).

**Comment by reinhapa** [comment]
@domric PR welcome 😎

**Comment by Gr33nbl00d** [comment]
I will have a look did not notice it yet

**Comment by Gr33nbl00d** [comment]
I think this is fixed @reinhapa
