### ISSUE TITLE
Configure a Message Converter

### ISSUE THREAD

**Issue by ignacio83** [reinhapa/rabbitmq-cdi#3]
Hi, Patrick
How are you?

Now we are need configure a message converter.
Actually the lib uses Jackson as provider. We are thinking of creating an interface named MessageConverter and configure that in PublisherConfiguration

What you think about?

This issues is critical for us, if you agree, we will make a pull request tomorow with this enhancement.

**Comment by reinhapa** [comment]
Hi Ignacio,

I thought also of making the transformation `EventObject <--> byte[]` customizable in the past. I was thinking similar like `javax.websocket.Encoder/Decoder` provided via CDI. There it would fall back to the Json Mapper if no specialized converter will be available, but I did'nt looked into it further...

So if you already got some idea of a solution that will fit your needs, create a PR that layout your thoughts..

Cheers Patrick

**Comment by reinhapa** [comment]
Closed with PR #4
