### ISSUE TITLE
Event Object Specific Routing Key / AMQP Properties

### ISSUE THREAD

**Issue by Gr33nbl00d** [reinhapa/rabbitmq-cdi#30]
I need the ability to modify routing key and/or AMQP Header Properties to route Messages differently based on the content of the object to send.
So the staticrouting key config and properties config per Class is not sufficient.
I have multiple ideas how to solve this one idea i had was that the routing key and properties are created / defined for each message with a strategy similar to encoder.
The idea is to modify the PublisherConfiguration class.

### Before:
```
void publish(Channel channel, Object event) throws EncodeException, IOException {
    byte[] data = ((Encoder<Object>) messageEncoder).encode(event);
    channel.basicPublish(exchange, routingKey, basicProperties, data);
}
```

### After:
```
void publish(Channel channel, Object event) throws EncodeException, IOException {
    byte[] data = ((Encoder<Object>) messageEncoder).encode(event);
   if(amqpHeaderRetriever != null)
   {
    routingKey=amqpHeaderRetriever.retrieverRoutingKey(event);
    basicProperties=amqpHeaderRetriever.retrieverProperties(event);
   }
    channel.basicPublish(exchange, routingKey, basicProperties, data);
}
```

What do you think about this Solution? I would implement this change if accepted via pull request

**Comment by reinhapa** [comment]
@Gr33nbl00d I see your solution, but I do not get quite the actual problem though. Don't you know the correct routing key and properties at the definition time?

**Comment by Gr33nbl00d** [comment]
Exactly the objects are google protocol buffer messages which i receive via a rest interface inside is a specific integer identifier and based on a configuration inside the database (mapping id to topic name) the messages need to be routed to different topics. Problem is that the number of oids is not fixed and will grow over time.

**Comment by Gr33nbl00d** [comment]
Now if im thinking about this i might have an even better idea...
The publish method inside PublisherConfiguration always seemed to be in the wrong place to me. I think because it is actualy  more than a pojo holding data. In fact it is more a kind of strategy but this is not visible from the name.

What about to let the user define his own PublishingStrategy which is stored in PublisherConfiguration

### Default Implementation
```
public class DefaultPublishingStrategy implements PublishingStrategy{
  public void publish(Channel channel, Object event, byte[] serializedEvent)
  {
    channel.basicPublish(exchange, routingKey, basicProperties, serializedEvent);
  }
```

### Custom Implementation
```
public class MyPublishingStrategy implements PublishingStrategy{
  public void publish(Channel channel, Object event, byte[] serializedEvent)
  {
     if (event.id==123)
      routingKey="specialrouting";
    channel.basicPublish(exchange, routingKey, basicProperties, serializedEvent);
  }
```

Benefit here is that i could also publish one event to multiple topics or even skip some. We also would get rid of the method publish in publisherConfiguration and instead let GenericPublisher simply call the publishing strategy which the publisher configuration holds.

**Comment by reinhapa** [comment]
I still do net get my head around the problem behind your presented solution though... What is the actual problem you're trying to solve?

**Comment by Gr33nbl00d** [comment]
Ok  i try to give you an example:
Imagine we have an Object LogEvent

```
class LogEvent {
  int severity;
  String message;
}
```

We have an exchange named logmessages which is of exchange type TOPIC

We want to forward Messages from severity 0-2 to topic verbose
and Messages with severity 3-5 to topic info.

As the routing key which is actually the topic name is defined while binding classes i would need an own class for each severity.

```
        bind(LogVerbose.class)
                .toExchange("logmessages")
                .withRoutingKey("verbose");

        bind(LogInfo.class)
                .toExchange("logmessages")
                .withRoutingKey("info");
```

This would force me to create wrapper classes and like i described in my example we are not only talking about 1-5 Log Level bug about a growing number of dynamical object identifiers so it is impossible to create classes while designing the system because i do not know which identifiers might be added in the future. So it would mean every new object identifiert would cause a software change which is no go for this application. 

with my solution i would define it the following:

```
//Second Solution:

        bind(LogEvent.class)
                .toExchange("logmessages")
                .withPublisherStrategy(new PublishBasedOnLogLevelStrategy());

//First Solution:

        bind(LogEvent.class)
                .toExchange("logmessages")
                .withAmqpHeaderRetriever(new RoutingKeyBasedOnLogLevelRetriever());


```

**Comment by reinhapa** [comment]
As far I can see you need calculate the routing key based on the event type. So my solution would be that you could optionally specify a something like a "routing key extractor" `java.util.function.Function` that takes a typed event object and returns a routing key as String instead of directly passing in the routing key.

The same could be done for the `BasicProperties` later on too...

**Comment by Gr33nbl00d** [comment]
i will try your implementation, i think this should solve my issues

**Comment by Gr33nbl00d** [comment]
Ok i tested it and it works for me :)

**Comment by reinhapa** [comment]
Sorry for the delay to get back to you on your comment about the extended publishing strategy. With the actual enhancement it is still possible to introduce a strategy later on as needed... But if the current solution is working for you now I will merge this into the current master then...
