### ISSUE TITLE
Unable to send RabbitMQ messages to Spring 

### ISSUE THREAD

**Issue by tonywestonuk** [reinhapa/rabbitmq-cdi#5]
Spring expects additional properties in the rabbit message header, for example "__TypeId__"

Please provide a mechanism to allow update of the message header (stored within PublisherConfiguration.BasicProperties ?)

**Comment by reinhapa** [comment]
@tonywestonuk  you could already set the basic properties using the `withProperties` method when configuring a new exchange binding.

**Comment by tonywestonuk** [comment]
Thanks, I didn't know about this :-D  This covers this request, so closing.
