### ISSUE TITLE
Messages consumed way

### ISSUE THREAD

**Issue by jeusdi** [reinhapa/rabbitmq-cdi#6]
I'd like to know how messages are consumed.

I mean:
 1. Are "messages" consumed one by one?
 2. Or "messages" are consumed according a "thread" is free? In this case, what's a "thread" here?

**Comment by reinhapa** [comment]
@jeusdi I don't get exactly what you wanted to know. Do you mean how messages are consumed from RabbitMQ and propagated as JavaEE events or the other way around?

**Comment by reinhapa** [comment]
@jeusdi I did not get any comment to my question in order to help you...
