### ISSUE TITLE
Multiple RabbitBinder and BindingInitializer for different vHosts

### ISSUE THREAD

**Issue by sbiermann** [reinhapa/rabbitmq-cdi#7]
Hi,
it is possible to have different RabbitBinder and BindingInitializer classes? In our application we have 2 different RabbitMQ vHosts, one for the application himself and a generall notification vHost for sending messages to the customer for example in case of an error in the application.

Kind regards
Stefan

**Comment by reinhapa** [comment]
@sbiermann you only need one BindingInitializer and one RabbitBinder per server configuration. Then inject the two binders into the initializer and start both (not jet tested but should work, as long as you do not have clashes on those endpoints:

```
@Singleton
@Startup
public class BindingInitializer {
  @Inject
  private RabbitBinderOne binderOne;
  @Inject
  private RabbitBinderTwo binderTwo;

  @PostConstruct
  public void initialize() {
    try {
      binderOne.configuration().setHost("somehost.somedomain")
      binderOne.setUsername("myuser").setPassword("mypassword");
      binderOne.initialize();

      binderTwo.configuration().setHost("somehost.somedomain")
      binderTwo.setUsername("myuser").setPassword("mypassword");
      binderTow.initialize();
    } catch (IOException e) {
      LoggerFactory.getLogger(getClass()).error("Unable to initialize", e);
    }
  }
}
```

**Comment by sbiermann** [comment]
I have tested it, 2 binder and 1 Initializer but it doesn't work.
`Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange 'notification.exchange' in vhost 'vhost1', class-id=60, method-id=40)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:484)
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:321)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:144)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:91)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:554)
	at java.lang.Thread.run(Thread.java:748)
`
The exchange "notification.exchange" is configured in Binder 2 and it is in vHost2, the exchanges and queues for vHost1 are configured in Binder 1.
Here is the initializing code without customer details
`
    @Inject
    private RabbitBinder binder;

    @Inject
    private RabbitNotificationBinder rabbitNotificationBinder;


    @PostConstruct
    public void initialize() {
        logger.info( "postConstruct called" );
        try {
            Properties properties = loadPropertiesForVhost1
            binder.configuration()
                    .setUsername( properties.getProperty( "rabbitmq.user" ) )
                    .setPassword( properties.getProperty( "rabbitmq.pwd" ) )
                    .setVirtualHost( "vHost1" );
            int port = Integer.parseInt( properties.getProperty( "rabbitmq.port" ) );
            String hosts = properties.getProperty( "rabbitmq.servers" );
            for( String host : hosts.split( "," ) ) {
                Address adr = new Address( host.trim(), port );
                binder.configuration().addHost( adr );
            }
            binder.initialize();

            properties = loadPropertiesForVhost2
            rabbitNotificationBinder.configuration().setUsername(properties.getProperty("rabbitmq.user"))
                    .setPassword(properties.getProperty("rabbitmq.pwd"))
                    .setVirtualHost("vHost2");
            port = Integer.parseInt(properties.getProperty("rabbitmq.port"));
            hosts = properties.getProperty("rabbitmq.servers");
            for (String host : hosts.split(",")) {
                Address adr = new Address(host.trim(), port);
                rabbitNotificationBinder.configuration().addHost(adr);
            }
            rabbitNotificationBinder.initialize();
            logger.info( "binder configured..." );
        }
        catch( IOException e ) {
            logger.error( "Unable to initialize", e );
        }
    }`

**Comment by reinhapa** [comment]
@sbiermann I need to set me up a similar setup to check that.. (did not have this requirement jet) So any PR in that direction would be welcome :-)
