### ISSUE TITLE
How can the ack signal send when no autoAck() is set?

### ISSUE THREAD

**Issue by sbiermann** [reinhapa/rabbitmq-cdi#76]
Hi,
i want to consume a RabbitMQ Message and after consuming i want to sent the ack signal to the RabbitMQ system. How can it be done with this library? I have only seen an internal method which is used when autoAck() is enabled. Enabling autoAck is not an option for the usecase.

Kind regards
Stefan

**Comment by reinhapa** [comment]
Hi Stefan,

The behaviour you are describing is done by default, when the event fire was successful or a nack signal is sent in case of an error.

-Patrick

**Comment by sbiermann** [comment]
The usecase is, that in the message which is stored in the RabbitMQ queue, containing up to 1000 different data objects which are stored in a database system. If the persisting of the 1000 different data objects is successful, the ack signal must be send at that point not earlier when the CDI event is fired.

**Comment by reinhapa** [comment]
Do you create up to 1000 event messages out of that single message then? If this is true, then this use case is not jet considered. The use case as for now was that for each message one event is being created and then fired and acknowleged upon successful delivery.

**Comment by sbiermann** [comment]
No, let's say there is a wrapper object with meta informations and in that wrapper object there are up to 1000 data objects as a list. The wrapper object is put into the RabbitMQ queue and get from it with your library and the CDI event is fired for this wrapper object. The object which observes the event will take the wrapper object and put some of the meta information and the data objects and persisting them to a database. After persisting this data objects the ack should send out to RabbitMQ for the wrapper object. 
In a container based environment like kubernetes it can happens that the container is stopped or killed and if the ack is send when the event of the wrapper object event is fired, it can be possible that data is lost forever. If no ack is send to RabbitMQ, the data will stay in the queue and when the container starts again, it will be proceed and no data is lost. Maybe there are some duplicates but this is acceptable and can be handled on the database layer.

**Comment by reinhapa** [comment]
> No, let's say there is a wrapper object with meta informations and in that wrapper object there are up to 1000 data objects as a list. The wrapper object is put into the RabbitMQ queue and get from it with your library and the CDI event is fired for this wrapper object. The object which observes the event will take the wrapper object and put some of the meta information and the data objects and persisting them to a database. After persisting this data objects the ack should send out to RabbitMQ for the wrapper object.
> 
That's handled by the actual implementation exactly in that way. If the event observer for the wrapper object is set to require a new transaction all should work as you expect. As soon the fire method is complete (an therefore the transaction has been committed to the database) an ack for the wrapper object is sent back to RabbitMQ. In all other cases no ack or even a nack (with requeue option) is sent to RabbitMQ. When the receiving part would go down no commit will be made for that wrapper object and also no ack will be sent back. In that case RabbitMQ considers the message a not delivered yet and the message should left in the queue. In case of the RabbitMQ goes down before the ack/nack is sent back the same holds true as described in the previous scenario.

-Patrick

**Comment by sbiermann** [comment]
Ok, sounds great. We will implement it that way.
